[2025-08-02T21:54:44.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T21:54:44.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_process_all_files_v2.process_json_file manual__2025-08-02T21:54:40.017662+00:00 [queued]>
[2025-08-02T21:54:44.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_process_all_files_v2.process_json_file manual__2025-08-02T21:54:40.017662+00:00 [queued]>
[2025-08-02T21:54:44.207+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-02T21:54:44.229+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_json_file> on 2025-08-02 21:54:40.017662+00:00
[2025-08-02T21:54:44.244+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1003) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-02T21:54:44.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_process_all_files_v2', 'process_json_file', 'manual__2025-08-02T21:54:40.017662+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/gcs_load_dag v2.py', '--cfg-path', '/tmp/tmpzx995j0d']
[2025-08-02T21:54:44.250+0000] {standard_task_runner.py:63} INFO - Started process 1019 to run task
[2025-08-02T21:54:44.250+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask process_json_file
[2025-08-02T21:54:44.901+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_process_all_files_v2.process_json_file manual__2025-08-02T21:54:40.017662+00:00 [running]> on host 06d424bf0ee1
[2025-08-02T21:54:45.064+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_process_all_files_v2' AIRFLOW_CTX_TASK_ID='process_json_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T21:54:40.017662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T21:54:40.017662+00:00'
[2025-08-02T21:54:45.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T21:54:45.082+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-02T21:54:45.089+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-02T21:54:45.090+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T21:54:45.091+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gcs_load_dag v2.py", line 19, in process_json_and_upload
    json_data_string = gcs_hook.download_as_string(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GCSHook' object has no attribute 'download_as_string'
[2025-08-02T21:54:45.119+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gcs_process_all_files_v2, task_id=process_json_file, run_id=manual__2025-08-02T21:54:40.017662+00:00, execution_date=20250802T215440, start_date=20250802T215444, end_date=20250802T215445
[2025-08-02T21:54:45.155+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task process_json_file ('GCSHook' object has no attribute 'download_as_string'; 1019)
[2025-08-02T21:54:45.871+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-02T21:54:45.916+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-02T21:54:45.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
